### ISSUE TITLE
problem with using the gdb script

### ISSUE THREAD

**Issue by niekbouman** [lenerd/fiber-gdb#1] opened 2021-01-29 22:24 UTC
Dear @lenerd,

I am trying to use your script to debug a Boost.Fiber application. 
(Thanks for sharing the script btw !)

However, after loading the script with "source fiber.py" in the gdb prompt, and loading my program,
when I issue `fiber main`, I get the following error:
```
>>> fiber main 
Traceback (most recent call last):
  File "fiber.py", line 280, in invoke
    scheduler = Scheduler.find()
  File "fiber.py", line 222, in find
    ctx = Context.find_active_context()
  File "fiber.py", line 87, in find_active_context
    ptr = gdb.parse_and_eval('boost::fibers::context::active()')
gdb.error: No type "context" within class or namespace "boost::fibers".
Error occurred in Python: No type "context" within class or namespace "boost::fibers".
```
Do you happen to know what I am doing wrong?

best,
Niek

**Comment by lenerd** [comment] 2021-01-29 22:36
Hi Niek,

if you have not done it already, Boost needs to be compiled with debug symbols.

Otherwise, I think I ran into the same problem a while ago. It seemed to be caused by the weird parsing rules that GDB uses for namespaces. I just noticed that I had unpushed commits locally which iirc fixed this issue. Please try if the latest version on master helps you.

**Comment by niekbouman** [comment] 2021-01-30 22:14
Thanks a lot for your help, I indeed hadn't realized that boost indeed needs debug symbols for this to work.

I am trying to better understand the script. I noticed that in your implementation you often read internal class variables, instead of using the API via the class methods, any particular reason for that? (One reason for preferring API use could be that it will be a bit more robust against new boost versions).
For example, in the Scheduler class , I added the following method, where I managed to call "has_ready_fibers()" class member function  by providing the this-ptr as first argument: 
```python
    def has_ready_fibers(self):
        fun = gdb.parse_and_eval("boost::fibers::scheduler::has_ready_fibers")
        return fun(self.ptr)
```
BTW, with boost 1.75, the design of the context class changed,in particular wait_hook_ has disappeared.

And, how about implementing the "is_sleeping" method by testing whether "the pointer of the current context is not equal to that the active context" ? Could that be a good idea?
```python
    def is_sleeping(self):
        ctx = Context.find_active_context()
        return ctx.ptr != self.ptr
```

Last question, how would I use the "fiber context" command (with bt or switch args) in a debugging session?

**Comment by niekbouman** [comment] 2021-01-30 22:22
NB I guess that the implementation strategy for "is_sleeping" that I outlined above would only work in single-thread setting...

**Comment by lenerd** [comment] 2021-01-30 23:14
The script emerged during a week-long debugging session to find the source of a deadlock. I was mostly pointer chasing through all the boost::intrusive lists. So the script was written to help me keep track of all the stuff and automate some steps. Of course it can be improved (and is open for contributions :).

> I am trying to better understand the script. I noticed that in your implementation you often read internal class variables, instead of using the API via the class methods, any particular reason for that? (One reason for preferring API use could be that it will be a bit more robust against new boost versions).

The is not particular reason for this, and I agree with you that the API should be used if possible. Unfortunately it won't work all the time:
- Sometime things are not exposed via the API, e.g. the scheduler's worker queue.
- Methods specified in header files might be inlined and therefore not available in the binary. So we cannot call them.

> For example, in the Scheduler class , I added the following method, where I managed to call "has_ready_fibers()" class member function by providing the this-ptr as first argument:
> 
> ```python
>     def has_ready_fibers(self):
>         fun = gdb.parse_and_eval("boost::fibers::scheduler::has_ready_fibers")
>         return fun(self.ptr)
> ```

That looks useful and clear! :)

> BTW, with boost 1.75, the design of the context class changed,in particular wait_hook_ has disappeared.

Good to know, I should look into that. Fortunately, I did not have to do any debugging with fibers lately.

> And, how about implementing the "is_sleeping" method by testing whether "the pointer of the current context is not equal to that the active context" ? Could that be a good idea?
> 
> ```python
>     def is_sleeping(self):
>         ctx = Context.find_active_context()
>         return ctx.ptr != self.ptr
> ```
> [...]
> NB I guess that the implementation strategy for "is_sleeping" that I outlined above would only work in single-thread setting...

You answered that already yourself. I used fibers with lot's of threads, which made the whole thing not really easier.

> Last question, how would I use the "fiber context" command (with bt or switch args) in a debugging session?

Often I had the case where some fibers got stuck. Then I would first get a list of all the worker fibers with `fiber workers`, which outputs a pointer to the context structure of every fiber. You can use `fiber context $pointer` to get more information about this fiber, e.g. register values. More helpful is usually `fiber context $pointer bt` to get a stack trace of the fiber, so you can see what it currently does or where it was blocked. Finally, `fiber context $pointer switch` makes a context switch to the fiber, and you can use standard GDB tools to inspect the stack frames etc. Since this essentially overwrites the current stack pointer and other registers, it might be useful to call `regstash push` before, so you can go back with `regstack pop`.

(I wrote this from memory and hope I remembered the workflow correctly. If more people than just me are interested, there should eventually be some documentation.)

Anyway, I am happy if this stuff is useful for other people. It definitely helped me to find problems more easily.

**Comment by niekbouman** [comment] 2021-01-31 11:01
Thanks !

> [...] and is open for contributions :)

I left a small pull request with minor additions (those adds are independent of the boost 1.75 changes)

**Comment by lenerd** [comment] 2021-12-14 18:43
> I left a small pull request with minor additions (those adds are independent of the boost 1.75 changes)

Finally merged ...

**Closed as completed by lenerd** 2021-12-14 18:43 UTC
